# Generated by Django 3.2.2 on 2021-05-19 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_funcionario_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='linkedin',
            field=models.CharField(default='#', max_length=100, verbose_name='Linkedin'),
        ),
    ]
